### ISSUE TITLE
PQ Topographic Shadow

### ISSUE THREAD

**Issue by benjimin** [GeoscienceAustralia/wagl#166]
Bit 14 of the pixel quality product definition should be implemented. (Could use code from WOfS.)

**Comment by sixy6e** [comment]
Bit 14 was going to use the shadow masks calculated as part of the NBAR workflow.  But PQ will be dropped sometime in the near future, and those shadow masks will persist as part of an ARD package. A prototype ARD package can be found [here](https://github.com/OpenDataCubePipelines/opendatacubepipeline.tesp/blob/master/tesp/_README.md).
