### ISSUE TITLE
Partial intersection with the satellite track

### ISSUE THREAD

**Issue by sixy6e** [GeoscienceAustralia/wagl#255]
**Sentinel-2 Granule**:

S2B_MSIL1C_20180716T021339_N0206_R060_T50HLG_20180716T060919.zip

The 60m resolution fails to calculate bisection coordinates, _wagl.satellite_solar_angles.track_bisection_, however the 10m and the 20m succeed.

**Error**
```pop from an empty set```

[code](https://github.com/GeoscienceAustralia/wagl/blob/develop/wagl/satellite_solar_angles.py#L225):

Essentially it fails if the only columns that the track intersects with is either the first or last column.  Technically it intersects, but for some reason the set difference logic ignores this possibility.

So instead of:
```python
column_bisection = ({first_row, last_row} - {0, cols-1, -1}).pop()
```
I tested
```python
column_bisection = ({first_row, last_row} - {-1}).pop()
```

which does succeed.

However,

The interpolation of the atmospheric coefficients, using the default (SHEAR) method, fails with an error of:

_Singular matrix_

_numpy.linalg.linalg.LinAlgError: Singular matrix_

I'd suggest for the time being that we simply ignore, but keep aware of the issue.  A re-work of the satellite and solar angles, as well as the sample locations at which to do the radiative transfer, is listed as future work, which might fix this issue.

**Comment by sixy6e** [comment]
@ASVincent & @uchchwhash it gets a little weirder.  I decided to test the SHEARB method of interpolation, and the granule now completes processing.
Future work is to test the different interpolation methods, and pick the best to act as the default method.

**Comment by ASVincent** [comment]
@sixy6e I had an example where the source imagery raised the 

> numpy.linalg.linalg.LinAlgError: Singular matrix error
without running into issues in the logic to determine in determining track intersection type (partial, full, none).
modifying the interpolation method to SHEARB still resulted in the same error.

I'll need to investigate the source imagery but for the record the source dataset was:

>/.../Sentinel-2/MSI/L1C/2018/2018-08/10S140E-15S145E/S2A_MSIL1C_20180803T004711_N0206_R102_T54LXM_20180803T021821.zip

md5sum 1d294d871c621a309753eba9bd98670e

**Comment by sixy6e** [comment]
Dang, was hoping that you might've had the same success, and we could make the simple switch to a different method.

**Comment by uchchwhash** [comment]
Thankfully this now has been solved. 🎉
