### ISSUE TITLE
Panchromatic bands

### ISSUE THREAD

**Issue by sixy6e** [GeoscienceAustralia/wagl#271]
We need to support the panchromatic bands.  The work required is fairly minimal, as the algorithm is already fairly generic.

* append pan bands into the sensors.json (they used to be there)
* define reflectance adjustment value
* re-work BRDF extraction to loop over multiple BRDF sources
    - calculate alpha-1 and alpha-2 values
    - average all alpha-1 and alpha-2 values

**Comment by sixy6e** [comment]
@uchchwhash and @ASVincent 

For the sensors.json file the "brdf_dataset" on the "brdf-collection-6" branch

https://github.com/GeoscienceAustralia/wagl/blob/brdf-collection-6/wagl/acquisition/sensors.json#L26

I think we could turn this into a list for all bands across each sensor.  That way the BRDF reader simply loops over all dataset items.  Something like:

```python
for brdf_ds_name in acq.brdf_dataset:
    retrieve()
```

Any thoughts?  Other ideas for simplicity and generality?

**Comment by uchchwhash** [comment]
Still waiting for Fuqin's review, but codebase-wise, this is resolved now.
