### ISSUE TITLE
Implement S2 ARD processing from Sinergise S2 L1C data

### ISSUE THREAD

**Issue by truth-quark** [GeoscienceAustralia/wagl#347]
TODO: enhance wagl so Sinergise S2 L1C data can be ard processed.

**Comment by uchchwhash** [comment]
What are the obstacles to this @truth-quark?

**Comment by truth-quark** [comment]
> What are the obstacles to this @truth-quark?

I think this might be done & I forgot to close it. @dunkgray  can you confirm the earlier Sinergise problem is gone?

**Comment by dunkgray** [comment]
Yes, this can be closed, as far as I know.

________________________________

**Comment by truth-quark** [comment]
Sinergise is already handled in wagl. This was a problem with some copied data DG was using for a test.
